### PR TITLE
Fix causality check typos

### PR DESCRIPTION
**Pull request by vihu**

### CODE REVIEW

**Comment by Vagabond** [comment]
If we can re-sync with this, then we can merge this. If it breaks sync it needs a chain var.

**Comment by vihu** [comment]
Ok, I was successfully able to resync with revalidation with this from block `450001`

**Comment by Vagabond** [comment]
If we can run another resync (since more SCs have closed since then), and it works, we should merge it

**Comment by vihu** [comment]
> If we can run another resync (since more SCs have closed since then), and it works, we should merge it

Sure, I'll do past ~150K blocks or so

**Comment by vihu** [comment]
> If we can run another resync (since more SCs have closed since then), and it works, we should merge it

Ok, was able to sync from block `450001` to the latest head with revalidation running this fix.

**Comment by Vagabond** [comment]
we should merge it then?

**Comment by vihu** [comment]
> we should merge it then?

We can I think, I've resynced twice with this (from block 450001). I can do one more run for completeness sake and go back to just before we activated state channels. If that syncs, _then_ we can 100% merge it. Will run it over the weekend.

**Comment by vihu** [comment]
Ok @Vagabond I think this is mergable. Appears to sync just fine, I've synced twice from `450001` and once from `339457` (that covers sc_v1 channels too).

**Review by evanmcc — APPROVED** [review]

**Pull request merged**
